# Generated by Django 4.2.2 on 2023-06-15 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('broker', models.CharField(max_length=100)),
                ('api_key', models.TextField()),
                ('secret_key', models.TextField()),
                ('account_balance', models.CharField(max_length=100)),
                ('initial_deposit', models.CharField(max_length=100)),
                ('net_profit', models.CharField(max_length=100)),
                ('withdrawal', models.CharField(max_length=100)),
                ('no_of_profit_trades', models.CharField(max_length=100)),
                ('no_of_loss_trades', models.CharField(max_length=100)),
                ('no_of_total_trades', models.CharField(max_length=100)),
                ('total_win_rate', models.CharField(max_length=100)),
                ('no_of_short_positions', models.CharField(max_length=100)),
                ('no_of_long_positions', models.CharField(max_length=100)),
                ('short_positions_won', models.CharField(max_length=100)),
                ('long_positions_won', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PENDING', 'Pending'), ('CLOSED', 'Closed')], default='PENDING', max_length=50)),
                ('time', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
                ('order_type', models.CharField(max_length=100)),
                ('order_size', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('stop_loss', models.CharField(max_length=100)),
                ('take_profit', models.CharField(max_length=100)),
                ('profit', models.CharField(max_length=100)),
                ('trigger_timeframe', models.CharField(max_length=100)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='edwizy_app.profile')),
                ('trigger_bot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='edwizy_app.bot')),
            ],
        ),
        migrations.AddField(
            model_name='bot',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='edwizy_app.profile'),
        ),
    ]
