# Generated by Django 4.2.2 on 2023-06-15 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edwizy_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='owner',
        ),
    ]
