# Generated by Django 4.2.2 on 2023-06-15 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edwizy_app', '0002_remove_bot_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trades',
        ),
    ]
