# Generated by Django 4.2.2 on 2023-06-15 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edwizy_app', '0003_delete_trades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PENDING', 'Pending'), ('CLOSED', 'Closed')], default='PENDING', max_length=50)),
                ('time', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
                ('order_type', models.CharField(max_length=100)),
                ('order_size', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('stop_loss', models.CharField(max_length=100)),
                ('take_profit', models.CharField(max_length=100)),
                ('profit', models.CharField(max_length=100)),
                ('trigger_timeframe', models.CharField(max_length=100)),
                ('owner', models.ManyToManyField(to='edwizy_app.profile')),
                ('trigger_bot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='edwizy_app.bot')),
            ],
        ),
    ]
