# Generated by Django 4.2.2 on 2023-06-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwizy_app', '0006_trades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trades',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('PENDING', 'PENDING'), ('CLOSED', 'CLOSED')], default='PENDING', max_length=50),
        ),
        migrations.CreateModel(
            name='Activebot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=100)),
                ('order_type', models.CharField(max_length=100)),
                ('order_size', models.CharField(max_length=100)),
                ('risk_reward', models.CharField(max_length=100)),
                ('bot', models.ManyToManyField(to='edwizy_app.bot')),
                ('owner', models.ManyToManyField(to='edwizy_app.profile')),
            ],
        ),
    ]
