# Generated by Django 4.2.2 on 2023-06-15 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edwizy_app', '0009_activebot_time_frame'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bot',
            old_name='bot_name',
            new_name='name',
        ),
    ]
