# Generated by Django 4.2.2 on 2023-06-16 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edwizy_app', '0010_rename_bot_name_bot_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activebot',
            name='bot',
        ),
        migrations.AddField(
            model_name='activebot',
            name='bot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='edwizy_app.bot'),
            preserve_default=False,
        ),
    ]
