# Generated by Django 4.2.2 on 2023-06-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwizy_app', '0011_remove_activebot_bot_activebot_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activebot',
            name='total_trades',
            field=models.CharField(default=0.0, max_length=100),
        ),
        migrations.AlterField(
            model_name='activebot',
            name='win_rate',
            field=models.CharField(default=0.0, max_length=100),
        ),
    ]
