# Generated by Django 4.2.2 on 2023-06-16 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edwizy_app', '0012_alter_activebot_total_trades_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activebot',
            name='owner',
        ),
        migrations.AddField(
            model_name='activebot',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='edwizy_app.profile'),
            preserve_default=False,
        ),
    ]
