# Generated by Django 4.2.2 on 2023-06-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwizy_app', '0016_alter_trades_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trades',
            name='profit',
            field=models.IntegerField(default=0),
        ),
    ]
