# Generated by Django 4.2.2 on 2023-06-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwizy_app', '0019_profile_long_positions_won_perc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('broker', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
                ('security_id', models.CharField(max_length=100)),
                ('exchange_segment', models.CharField(max_length=100)),
                ('instrument_type', models.CharField(max_length=100)),
            ],
        ),
    ]
