# Generated by Django 4.2.2 on 2023-06-27 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edwizy_app', '0020_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbol',
            name='symbol',
        ),
    ]
