# Generated by Django 4.2.2 on 2023-06-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwizy_app', '0024_symbol_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='total_trades',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='win_rate',
        ),
        migrations.AddField(
            model_name='symbol',
            name='total_trades',
            field=models.CharField(default=0.0, max_length=100),
        ),
        migrations.AddField(
            model_name='symbol',
            name='win_rate',
            field=models.CharField(default=0.0, max_length=100),
        ),
    ]
