# Generated by Django 4.2.2 on 2023-06-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwizy_app', '0025_remove_bot_total_trades_remove_bot_win_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='max_trade',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='order_size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='order_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='risk_reward',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='time_frame',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
