# Generated by Django 4.2.2 on 2023-06-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwizy_app', '0026_profile_max_trade_profile_order_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='camarilla',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dare_to_trade',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fibonacci',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='price_action',
            field=models.BooleanField(default=True),
        ),
    ]
