# Generated by Django 4.2.2 on 2023-06-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edwizy_app', '0027_profile_camarilla_profile_dare_to_trade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_chart',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
