# Generated by Django 4.2.2 on 2023-06-30 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edwizy_app', '0028_profile_active_chart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbolbot',
            name='bot',
        ),
        migrations.RemoveField(
            model_name='symbolbot',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='trigger_bot',
        ),
        migrations.DeleteModel(
            name='Bot',
        ),
        migrations.DeleteModel(
            name='SymbolBot',
        ),
    ]
