# Generated by Django 4.2.2 on 2023-07-03 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edwizy_app', '0029_remove_symbolbot_bot_remove_symbolbot_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='bot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='edwizy_app.strategies'),
        ),
    ]
